#!/bin/sh

set -u # Treat unset variables as an error.
sudo chown abc:abc -R /cfg
sudo chmod +755 -R /cfg
sudo chown abc:abc -R /defaults
sudo chmod +755 -R /defaults

java -jar /defaults/JDownloader.jar

trap "terminate" TERM QUIT INT

# JDownloader logs all environment variables.  Make sure the MyJDownloader
# credentials don't leak.
unset MYJDOWNLOADER_EMAIL
unset MYJDOWNLOADER_PASSWORD

log_debug() {
    if is-bool-val-true "${CONTAINER_DEBUG:-0}"; then
        echo "$@"
    fi
}

is_jd_running() {
    pgrep java >/dev/null
}

start_jd() {
	java /defaults/JDownloader.jar
}

kill_jd() {
    # Kill JDownloader.
    killall java 2>/dev/null

    # Wait for JDownloader to terminate.
    while is_jd_running; do
        sleep 0.25
    done
}

terminate() {
    log_debug "terminating JDownloader2..."
    kill_jd
    log_debug "JDownloader2 terminated."
    exit 0
}

# Start JDownloader.
#
# NOTE: Because JDownloader can restart itself (e.g. during an update), we have
#       to launch JDownloader in background and monitor its status. This is
#       needed to make sure the container doesn't terminate itself during a
#       restart of JDownloader.
log_debug "starting JDownloader2..."
start_jd

# Wait until it dies.
wait $!

# Now monitor its state. At this point, we cannot "wait" on the process since
# it has not been launched by us.
while true
do
    if ! is_jd_running; then
        log_debug "JDownloader2 not running, exiting..."
        break
    fi
    sleep 1
done

# vim:ft=sh:ts=4:sw=4:et:sts=4
